name: Node.js API CI

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: '14.x'
      - uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
           heroku_app_name: "travelguideuserapi"
           heroku_email: "hsaddouki@gmail.com"
      - name: Install dependencies
      run: npm install
      - name: Compile typescript files
      run: tsc
      - name: Run API
      run: npm run start
